[tool.poetry]
name = "viaf-to-turtle"
version = "0.1.0"
description = ""
authors = ["mattecasu <mattecasu@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
rdflib = "^7.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
